# datasource
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    generate-unique-name: false

  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT}